baseURL: https://coursehugoscss.netlify.app/
languageCode: en-au
title: Hugo SCSS Building
# alternate copyright company text
copyright: Sean Emerson
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length on list pages
summaryLength: 7
# this is required so that Hugo will render markdown to HTML
markup:
  goldmark:
    renderer:
      unsafe: true

# menu links via config file
menu:
  main:
  - name: Github
    url: http://www.github.com/
    weight: 90
    params:
      blank: true
  - name: Google
    url: http://www.google.com/
    weight: 100
    params:
      blank: true